::: {.content-visible when-profile="fr"}
---
title: "Projet 2 - Interaction avec des APIs"
---

## Contexte du projet

Il y a certains jours où l'on serait bien resté en télétravail.. Parmi ceux-là, ces jours à la fois humides et venteux où il est impossible de maintenir une coiffure décente, malgré tous ses efforts. Pourrait-on utiliser `Python` pour prédire ce que les anglo-saxons nomment des *bad hair day* ("mauvais jour de cheveux") ?

L'objectif du projet est de construire un *bad hair index* ("indice de mauvais jour de cheveux") à partir des données météorologiques et de représenter graphiquement l'évolution de cette indice afin de déterminer à l'avance les jours où l'on ferait mieux de rester bien au chaud. Afin d'obtenir les données adéquates, nous allons requêter des APIs.

Une API (Interface de Programmation d'Application) est un ensemble de règles et de spécifications que les applications suivent pour communiquer entre elles. Elle permet à votre code d'**accéder à des fonctionnalités externes ou à des données**, comme celles de bases de données météorologiques ou de services de localisation. Lorsqu'on parle de requêtage d'une API, cela se fait généralement via le **protocole HTTP**, qui est le même protocole utilisé pour charger des pages web. Dans ce tutoriel, nous utiliserons le package [requests](https://fr.python-requests.org/en/latest/), qui simplifie le processus de requêtage et de gestion de réponses HTTP.

Les APIs que nous allons utiliser sont :

- [Nominatim](https://nominatim.org/release-docs/latest/api/Overview/) : une API de géocodage proposée par **OpenStreetMap** qui nous permet de convertir un nom de lieu en coordonnées géographiques.
- [Open-Meteo Weather Forecast](https://open-meteo.com/en/docs) : une API qui fournit des prévisions météorologiques détaillées. 

Commençons par importer les packages dont nous aurons besoin au cours de ce projet.

```{python}
import requests
import pandas
import seaborn as sns
import matplotlib.pyplot as plt
```

## Partie 1 : récupération des coordonnées géographiques pour une localisation donnée

L'API de prédiction d'open-meteo prend en entrée les coordonnées géographiques (latitude, longitude) du lieu où seront réalisées les prédictions. On pourrait récupérer manuellement les coordonnées du lieu qui nous intéresse, mais cela limiterait la reproductibilité de nos analyses avec d'autres lieux que celui choisi. On va donc utiliser une seconde API, `Nominatim`, pour obtenir ces coordonnées pour un lieu donné.

Lorsque l'on travaille à partir d'une API, la première étape est toujours de lire sa documentation. C'est elle qui indique à quelle adresse nous devons envoyer nos requêtes, sous quel format, et ce que va nous répondre l'API. Dans notre cas, la docuemntation de `Nominatim` se trouve à [cette adresse](https://nominatim.org/release-docs/develop/api/Overview/). N'hésitez pas à la parcourir rapidement pour évaluer les possibilités de l'API.

### Question 1

La première caractéristique essentielle d'une API est le *endpoint*, c'est à dire l'URL à laquelle on va envoyer des requêtes. Dans notre cas, on va utiliser le *endpoint* `/search` dans la mesure où l'on veut trouver un objet géographique (des coordonnées) à partir d'un nom de localisation. La [page de documentation]([/search](https://nominatim.org/release-docs/develop/api/Search/)) associée à ce *endpoint* nous donne toutes les informations dont nous avons besoin :

- le format d'une requête est `https://nominatim.openstreetmap.org/search?<params>` où `<params>` doit être remplacé par les paramètres de la requête, séparés par le symbole `&`
- dans la section [Structured Query](https://nominatim.org/release-docs/develop/api/Search/#structured-query), on voit que l'API admet comme paramètres `country` (pays) et `city` (ville), que l'on va utiliser pour paramétrer notre requête. 

Définissez une fonction `build_request_nominatim` qui construit le lien de la requête pour un pays et une ville donnée.

#### Résultat attendu

```{python}
url_request_nominatim = solutions.build_request_nominatim("France", "Montrouge")
url_request_nominatim
```

#### À vous de jouer !

```{python}
def build_request_nominatim(country, city):
    # Votre code ici
    return url_request
```

```{python}
# Vérification du résultat
url_request_nominatim = build_request_nominatim("France", "Montrouge")
url_request_nominatim
```

### Question 2

La prochaine étape est d'envoyer notre requête paramétrisée à l'API. Pour la tester au préalable, on peut simplement mettre l'adresse dans un navigateur et voir ce que nous renvoie l'API. Si les résultats ont l'air cohérent, on peut continuer. Si l'API nous renvoie un code d'erreur, il y a sûrement une erreur à trouver dans la requête. 

Pour effectuer cette requête à partir de `Python` afin d'en récupérer les résultats, on utilise la fonction `requests.get()` à laquelle on fournit comme seul paramètre l'URL de la requête. On obtient en retour un objet "réponse", dont on peut extraire le contenu `JSON` sous forme d'un dictionnaire `Python` en lui appliquant la méthode `.json()`. Il faut alors parcourir le dictionnaire pour en extraire les informations pertinentes ; dans notre cas : la latitude et la longitude.

Définissez une fonction `get_lat_long` qui récupère la latitude et la longitude (centrale) pour un pays et une ville donnée.

#### Résultat attendu

```{python}
lat, long = solutions.get_lat_long(query=url_request_nominatim)
print(lat, long)
print(type(lat))
print(type(long))
```

#### À vous de jouer !

```{python}
def get_lat_long(query):
    # Votre code ici
    return latitude, longitude
```

```{python}
# Vérification du résultat
lat, long = get_lat_long(query=url_request_nominatim)
print(lat, long)
print(type(lat))
print(type(long))
```

## Partie 2 : récupération des prévisions météorologiques

Maintenant que nous pouvons récupérer les coordonnées associées à une localisation donnée, nous pouvons requêter l'API `open-meteo.com` pour obtenir les données de prédiction météo associées à ces coordonnées. Là encore, la première étape est de s'intéresser à la documentation ([page d'accueil](https://open-meteo.com/), [doc](https://open-meteo.com/en/docs)), qui nous fournit plusieurs informations :

- le *endpoint* pour l'API de prédiction est `https://api.open-meteo.com/v1/forecast`
- l'API attend en entrée une `latitude` et une `latitude`, ainsi que les variables météorologiques souhaitées. Pour notre problématique, nous allons récupérer des informations sur le taux d'humidité (`relativehumidity_2m`) et la vitesse du vent (`windspeed_10m`)
- par défaut, l'API renvoie des prédictions à 7 jours

### Question 3

Sachant toutes ces informations et en vous aidant de la documentation, définissez une fonction `build_request_open_meteo` qui construit le lien de la requête pour une latitude et une longitude donnée. Là encore, il est possible de tester la validité de la requête en exécutant le lien dans un navigateur et en vérifiant que les résultats retournés paraissent cohérents.

#### Résultat attendu

```{python}
url_request_open_meteo = solutions.build_request_open_meteo(latitude=lat, longitude=long)
url_request_open_meteo
```

#### À vous de jouer !

```{python}
def build_request_open_meteo(latitude, longitude):
    # Votre code ici
    return url_request
```

```{python}
# Vérification du résultat
url_request_open_meteo = build_request_open_meteo(latitude=lat, longitude=long)
url_request_open_meteo
```

### Question 4

A nouveau, on utilise la fonction `requests.get()` pour soumettre la requête à l'API. On obtient en retour un objet "réponse", dont on peut extraire le contenu `JSON` sous forme d'un dictionnaire `Python` en lui appliquant la méthode `.json()`.

Mais que se passe-t-il dans le cas où la requête soumise est invalide (faute de frappe, paramètres inexistants, etc.) ? Dans ce cas, l'API nous renvoie une erreur. L'objet réponse de la requête contient un attribut `.status_code` qui donne le code de réponse d'une requête. Le code `200` indique la réussite d'une requête ; tout autre code indique une erreur.

Définissez une fonction `get_meteo_data` qui récupère le dictionnaire complet de données retourné par l'API suite à notre requête. Le comportement de la fonction doit cependant dépendre du code de réponse de la requête :

- si le code vaut `200`, la fonction renvoie le dictionnaire des prédictions ;
- si le code est différent de `200`, la fonction affiche le code d'erreur et renvoie `None`.

#### Résultat attendu

```{python}
predictions = solutions.get_meteo_data(url_request_open_meteo)
type(predictions)
```

```{python}
wrong_request = solutions.build_request_open_meteo(latitude=lat, longitude="dix-sept-virgule-quatre")
output = solutions.get_meteo_data(wrong_request)
print(output)
```

#### À vous de jouer !

```{python}
def get_meteo_data(query):
    # Votre code ici
    return response.json()
```

```{python}
# Vérification du résultat
predictions = get_meteo_data(url_request_open_meteo)
type(predictions)
```

```{python}
# Vérification du résultat
wrong_request = build_request_open_meteo(latitude=lat, longitude="dix-sept-virgule-quatre")
output = get_meteo_data(wrong_request)
print(output)
```

### Question 5

Afin de bien comprendre la structure des données que nous avons récupérées, explorez le dictionnaire des prédictions retourné par l'API (clefs, différents niveaux, format des prédictions, format de la variable indiquant les dates/heures des prédictions, etc.)

```{python}
#| code-fold: true
#| code-summary: "Afficher le code"

# Exploration des données
print(type(predictions))
print(predictions.keys())
print(type(predictions["hourly"]))
print(predictions["hourly"].keys())
print(type(predictions["hourly"]["time"]))
print()

# Afficher les données
print(predictions['hourly']["time"][:5])
print(predictions['hourly']["time"][-5:])
print()
print(predictions['hourly']["relativehumidity_2m"][:5])
print(predictions['hourly']["windspeed_10m"][:5])
```

## Partie 3 : construction et visualisation d'un *bad hair index*

L'objectif de cette dernière partie est de calculer et représenter graphiquement le *bad hair index*. Rappelons que l'on définit cet indice comme le **produit de l'humidité relative et de la vitesse du vent**. Il s'agit d'une mesure ludique de la probabilité d'avoir une "mauvaise coiffure" en raison des conditions météorologiques.

### Question 6

Définissez une fonction `preprocess_predictions` qui met en forme les prédictions issues de l'API sous forme d'un `DataFrame Pandas` en vue d'une analyse statistique. Les étapes à implémenter sont les suivantes :

1. convertir les données prédites en un `DataFrame Pandas` à 3 colonnes (date et heure de l'observation, humidité, vitesse du vent) ;
2. convertir la colonne de temps au format `datetime` ([documentation](https://pandas.pydata.org/docs/reference/api/pandas.to_datetime.html))
3. ajouter deux nouvelles variables indiquant le jour de l'observation et l'heure de l'observation
4. ajouter une variable qui calcule le *bad hair index*

#### Résultat attendu

```{python}
df_preds = solutions.preprocess_predictions(predictions)
df_preds.head()
```

#### À vous de jouer !

```{python}
def preprocess_predictions(predictions):
    # Votre code ici
    return df
```

```{python}
# Vérification du résultat
df_preds = preprocess_predictions(predictions)
df_preds.head()
```

### Question 7

A des fins de représentation graphique, nous allons représenter le *bad hair index* agrégé à deux niveaux :

- moyenne heure par heure. Cela permettra de répondre à la question : "à quel heure sera-t-il généralement préférable de rester à la maison la semaine prochaine ?"
- moyenne jour par jour. Cela permettra de répondre à la question : "quel jour sera-t-il généralement préférable de rester à la maison la semaine prochaine ?"

Définissez une fonction `plot_agg_avg_bhi` qui calcule l'indice agrégé dans chaque cas, et représente le résultat sous la forme d'un `lineplot`.

#### Résultat attendu

```{python}
solutions.plot_agg_avg_bhi(df_preds, agg_var="day")
```

```{python}
solutions.plot_agg_avg_bhi(df_preds, agg_var="hour")
```

#### À vous de jouer !

```{python}
def plot_agg_avg_bhi(df_preds, agg_var="day"):
    # Votre code ici
    return None
```

```{python}
# Vérification du résultat
plot_agg_avg_bhi(df_preds, agg_var="day")
```

```{python}
# Vérification du résultat
plot_agg_avg_bhi(df_preds, agg_var="hour")
```

Qu'en concluez-vous pour la semaine à venir ?

### Question 8

Notre outil de prévision des *bad hair days* fonctionne à merveille. Mais c'est bientôt les vacances, et un voyage à Berlin est prévu. Idéalement, on voudrait pouvoir utiliser notre outil pour n'importe quelle localité. Heureusement, on a défini à chaque étape des fonctions, ce qui va nous permettre de passer facilement à une fonction "chef d'orchestre" qui appelle toutes les autres pour une localité donnée.

Définissez une fonction `main` qui représente le *bad hair index* pour un pays, une ville et un niveau d'agrégation donnés.

#### Résultat attendu

```{python}
solutions.main(country="Germany", city="Berlin", agg_var="day")
```

```{python}
solutions.main(country="Germany", city="Berlin", agg_var="hour")
```

#### À vous de jouer !

```{python}
def main(country, city, agg_var="day"):
    # Votre code ici
    return None
```

```{python}
# Vérification du résultat
main(country="Germany", city="Berlin", agg_var="day")
```

```{python}
# Vérification du résultat
main(country="Germany", city="Berlin", agg_var="hour")
```

:::















::: {.content-visible when-profile="en"}

---
title: "Project 2 - Interaction with APIs"
---

## Project context

There are some days when one would prefer to stay working from home... Among those days are the ones that are both humid and windy, making it impossible to maintain a decent hairstyle despite all efforts. Could we use `Python` to predict what the Anglo-Saxons call *bad hair days*?

The goal of the project is to construct a *bad hair index* from weather data and graphically represent the evolution of this index to determine in advance the days when it's better to stay warm inside. To obtain the appropriate data, we will query APIs.

An API (Application Programming Interface) is a set of rules and specifications that applications follow to communicate with each other. It allows your code to **access external functionalities or data**, such as those from weather databases or location services. When querying an API, it is generally done via the **HTTP protocol**, which is the same protocol used to load web pages. In this tutorial, we will use the [requests](https://docs.python-requests.org/en/latest/) package, which simplifies the process of querying and handling HTTP responses.

The APIs we will use are:

- [Nominatim](https://nominatim.org/release-docs/latest/api/Overview/): a geocoding API provided by **OpenStreetMap** that allows us to convert a place name into geographic coordinates.
- [Open-Meteo Weather Forecast](https://open-meteo.com/en/docs): an API that provides detailed weather forecasts.

Let's start by importing the packages we will need throughout this project.

```{python}
import requests
import pandas
import seaborn as sns
import matplotlib.pyplot as plt
```

## Part 1: Retrieving geographic coordinates for a given location

The Open-Meteo prediction API takes as input the geographic coordinates (latitude, longitude) of the location where predictions will be made. We could manually retrieve the coordinates of the location of interest, but this would limit the reproducibility of our analyses with other locations than the one chosen. We will therefore use a second API, `Nominatim`, to obtain these coordinates for a given place.

When working with an API, the first step is always to read its documentation. It indicates the address to which we must send our requests, in what format, and what the API will return. In our case, the documentation for `Nominatim` can be found [here](https://nominatim.org/release-docs/develop/api/Overview/). Feel free to browse through it quickly to evaluate the possibilities of the API.

### Question 1

The first essential characteristic of an API is the *endpoint*, which is the URL to which we will send requests. In our case, we will use the *endpoint* `/search` since we want to find a geographic object (coordinates) from a location name. The [documentation page](https://nominatim.org/release-docs/develop/api/Search/) associated with this *endpoint* gives us all the information we need:

- the format of a request is `https://nominatim.openstreetmap.org/search?<params>` where `<params>` should be replaced by the request parameters, separated by the `&` symbol
- in the [Structured Query](https://nominatim.org/release-docs/develop/api/Search/#structured-query) section, we see that the API accepts parameters `country` and `city`, which we will use to parameterize our request.

Define a function `build_request_nominatim` that constructs the request URL for a given country and city.

#### Expected result

```{python}
url_request_nominatim = solutions.build_request_nominatim("France", "Montrouge")
url_request_nominatim
```

#### Your turn!

```{python}
def build_request_nominatim(country, city):
    # Your code here
    return url_request
```

```{python}
# Checking the result
url_request_nominatim = build_request_nominatim("France", "Montrouge")
url_request_nominatim
```

### Question 2

The next step is to send our parameterized request to the API. To test it beforehand, we can simply put the address in a browser and see what the API returns. If the results look coherent, we can continue. If the API returns an error code, there is likely an error in the request.

To perform this request from `Python` to retrieve the results, we use the `requests.get()` function to which we provide the request URL as the only parameter. We get back a "response" object, from which we can extract the JSON content as a `Python` dictionary by applying the `.json()` method. We then need to parse the dictionary to extract the relevant information; in our case: latitude and longitude.

Define a function `get_lat_long` that retrieves the central latitude and longitude for a given country and city.

#### Expected result

```{python}
lat, long = solutions.get_lat_long(query=url_request_nominatim)
print(lat, long)
print(type(lat))
print(type(long))
```

#### Your turn!

```{python}
def get_lat_long(query):
    # Your code here
    return latitude, longitude
```

```{python}
# Checking the result
lat, long = get_lat_long(query=url_request_nominatim)
print(lat, long)
print(type(lat))
print(type(long))
```

## Part 2: Retrieving weather forecasts

Now that we can retrieve the coordinates associated with a given location, we can query the `open-meteo.com` API to get the associated weather forecast data. Again, the first step is to look at the documentation ([homepage](https://open-meteo.com/), [doc](https://open-meteo.com/en/docs)), which provides us with several pieces of information:

- the *endpoint* for the prediction API is `https://api.open-meteo.com/v1/forecast`
- the API expects as input a `latitude` and a `longitude`, as well as the desired weather variables. For our problem, we will retrieve information on relative humidity (`relativehumidity_2m`) and wind speed (`windspeed_10m`)
- by default, the API returns 7-day forecasts

### Question 3

Knowing all this information and using the documentation, define a function `build_request_open_meteo` that constructs the request URL for a given latitude and longitude. Again, it is possible to test the validity of the request by executing the link in a browser and verifying that the returned results seem coherent.

#### Expected result

```{python}
url_request_open_meteo = solutions.build_request_open_meteo(latitude=lat, longitude=long)
url_request_open_meteo
```

#### Your turn!

```{python}
def build_request_open_meteo(latitude, longitude):
    # Your code here
    return url_request
```

```{python}
# Checking the result
url_request_open_meteo = build_request_open_meteo(latitude=lat, longitude=long)
url_request_open_meteo
```

### Question 4

Again, we use the `requests.get()` function to submit the request to the API. We get back a "response" object, from which we can extract the JSON content as a `Python` dictionary by applying the `.json()` method.

But what happens if the submitted request is invalid (typo, nonexistent parameters, etc.)? In this case, the API returns an error. The response object of the request contains an attribute `.status_code` that gives the response code of a request. The code `200` indicates a successful request; any other code indicates an error.

Define a function `get_meteo_data` that retrieves the complete data dictionary returned by the API following our request. The function's behavior should depend on the request's response code:

- if the code is `200`, the function returns the predictions dictionary;
- if the code is different from `200`, the function displays the error code and returns `None`.

#### Expected result

```{python}
predictions = solutions.get_meteo_data(url_request_open_meteo)
type(predictions)
```

```{python}
wrong_request = solutions.build_request_open_meteo(latitude=lat, longitude="seventeen-point-four")
output = solutions.get_meteo_data(wrong_request)
print(output)
```

#### Your turn!

```{python}
def get_meteo_data(query):
    # Your code here
    return response.json()
```

```{python}
# Checking the result
predictions = get_meteo_data(url_request_open_meteo)
type(predictions)
```

```{python}
# Checking the result
wrong_request = build_request_open_meteo(latitude=lat, longitude="seventeen-point-four")
output = get_meteo_data(wrong_request)
print(output)
```

### Question 5

To understand the structure of the data we retrieved, explore the returned predictions dictionary (keys, different levels, format of the predictions, format of the variable indicating the dates/times of the predictions, etc.)

```{python}
#| code-fold: true
#| code-summary: "Show code"

# Data exploration
print(type(predictions))
print(predictions.keys())
print(type(predictions["hourly"]))
print(predictions["hourly"].keys())
print(type(predictions["hourly"]["time"]))
print()

# Display the data
print(predictions['hourly']["time"][:5])
print(predictions['hourly']["time"][-5:])
print()
print(predictions['hourly']["relativehumidity_2m"][:5])
print(predictions['hourly']["windspeed_10m"][:5])
```

## Part 3: Constructing and visualizing a *bad hair index*

The goal of this last part is to calculate and graphically represent the *bad hair index*. Recall that we define this index as the **

product of relative humidity and wind speed**. It is a playful measure of the likelihood of having a "bad hair day" due to weather conditions.

### Question 6

Define a function `preprocess_predictions` that formats the predictions from the API into a `Pandas DataFrame` for statistical analysis. The steps to implement are as follows:

1. convert the predicted data into a 3-column `Pandas DataFrame` (observation date and time, humidity, wind speed);
2. convert the time column to `datetime` format ([documentation](https://pandas.pydata.org/docs/reference/api/pandas.to_datetime.html))
3. add two new variables indicating the observation day and the observation hour
4. add a variable that calculates the *bad hair index*

#### Expected result

```{python}
df_preds = solutions.preprocess_predictions(predictions)
df_preds.head()
```

#### Your turn!

```{python}
def preprocess_predictions(predictions):
    # Your code here
    return df
```

```{python}
# Checking the result
df_preds = preprocess_predictions(predictions)
df_preds.head()
```

### Question 7

For graphical representation purposes, we will represent the aggregated *bad hair index* at two levels:

- average hour by hour. This will answer the question: "at what time will it generally be preferable to stay home next week?"
- average day by day. This will answer the question: "which day will it generally be preferable to stay home next week?"

Define a function `plot_agg_avg_bhi` that calculates the aggregated index in each case and represents the result as a `lineplot`.

#### Expected result

```{python}
solutions.plot_agg_avg_bhi(df_preds, agg_var="day")
```

```{python}
solutions.plot_agg_avg_bhi(df_preds, agg_var="hour")
```

#### Your turn!

```{python}
def plot_agg_avg_bhi(df_preds, agg_var="day"):
    # Your code here
    return None
```

```{python}
# Checking the result
plot_agg_avg_bhi(df_preds, agg_var="day")
```

```{python}
# Checking the result
plot_agg_avg_bhi(df_preds, agg_var="hour")
```

What do you conclude for the coming week?

### Question 8

Our *bad hair days* prediction tool works wonderfully. But it's almost vacation time, and a trip to Berlin is planned. Ideally, we would like to use our tool for any location. Fortunately, we have defined functions at each step, which will allow us to easily move on to an "orchestrator" function that calls all the others for a given location.

Define a `main` function that represents the *bad hair index* for a given country, city, and aggregation level.

#### Expected result

```{python}
solutions.main(country="Germany", city="Berlin", agg_var="day")
```

```{python}
solutions.main(country="Germany", city="Berlin", agg_var="hour")
```

#### Your turn!

```{python}
def main(country, city, agg_var="day"):
    # Your code here
    return None
```

```{python}
# Checking the result
main(country="Germany", city="Berlin", agg_var="day")
```

```{python}
# Checking the result
main(country="Germany", city="Berlin", agg_var="hour")
```


:::