project:
  type: website
  render:
    - '*.qmd'

website:
  title: "Formation SSPy {{< fa brands python >}}"
  sidebar:
    style: 'docked'
    contents:
      - section: "Fondamentaux du langage"
        contents: 
          - source/fundamentals/types-variables/tutorial.qmd
          - source/fundamentals/data-structures1/tutorial.qmd
          - source/fundamentals/data-structures2/tutorial.qmd
          - source/fundamentals/tests/tutorial.qmd
          - source/fundamentals/loops/tutorial.qmd
          - source/fundamentals/functions/tutorial.qmd
          - source/fundamentals/oop/tutorial.qmd
      - section: "Manipulation de données"
        contents: 
          - source/manipulation/modules-files/tutorial.qmd
          - source/manipulation/csv-json-files/tutorial.qmd
          - source/manipulation/numpy/tutorial.qmd
          - source/manipulation/pandas/tutorial.qmd
          - source/manipulation/dataviz/tutorial.qmd
      - section: "Projets"
        contents: 
          - source/projects/puissance4/tutorial.qmd
          - source/projects/meteo/tutorial.qmd
          - source/projects/RP/tutorial.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-annotations: hover
    code-link: true
    execute:
      echo: true
      eval: true
      output: true
      warning: true
      error: true
