website:
  title: "Formation SSPy {{< fa brands python >}}"
  sidebar:
    style: 'docked'
    contents:
      - section: "Fondamentaux du langage"
        contents: 
          - source/fr/fundamentals/types-variables/tutorial.qmd
          - source/fr/fundamentals/data-structures1/tutorial.qmd
          - source/fr/fundamentals/data-structures2/tutorial.qmd
          - source/fr/fundamentals/tests/tutorial.qmd
          - source/fr/fundamentals/loops/tutorial.qmd
          - source/fr/fundamentals/functions/tutorial.qmd
          - source/fr/fundamentals/oop/tutorial.qmd
      - section: "Manipulation de données"
        contents: 
          - source/fr/manipulation/modules-files/tutorial.qmd
          - source/fr/manipulation/csv-json-files/tutorial.qmd
          - source/fr/manipulation/numpy/tutorial.qmd
          - source/fr/manipulation/pandas/tutorial.qmd
          - source/fr/manipulation/dataviz/tutorial.qmd
      - section: "Projets"
        contents: 
          - source/fr/projects/puissance4/tutorial.qmd
          - source/fr/projects/meteo/tutorial.qmd
          - source/fr/projects/RP/tutorial.qmd
