project:
  type: website
  render:
    - '*.qmd'

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-annotations: hover
    code-link: true
    execute:
      echo: true
      eval: true
      output: true
      warning: true
      error: true
