name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-doc:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2.3.0

      - name: Build course doc
        run: |
          python generate-doc.py
          cat doc-course.json
