name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  update-doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2.3.0

      - name: Build doc
        id: builddoc
        run: |
          python generate-doc.py
          content=`cat doc-course.txt`
          payload=`echo \'{ \"educational_resources\": \"$content\" }\'`
          echo "PAYLOAD=$(echo $payload)" >> $GITHUB_ENV
          
      - run: |
          echo $PAYLOAD
          
#       - name: Dispatch doc
#         uses: peter-evans/repository-dispatch@v1
#         with:
#           token: ${{ secrets.PAT_FOR_DISPATCH }}
#           event-type: update_educational_resources
#           repository: InseeFrLab/www.sspcloud.fr
#           client-payload: ${{ steps.builddoc.outputs.doc }}
