name: Publish slides and notebooks

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install the default version of uv
        id: setup-uv
        uses: astral-sh/setup-uv@v7

      - name: Set up quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render FR and EN version
        run: |
          uv run quarto render --profile fr
          uv run quarto render --profile en

      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          render: false
          target: gh-pages
